### ISSUE TITLE
not able to connect to hostie

### ISSUE THREAD

**Issue by iyjian** [juzibot/wxwork-tester#28]
> Important：Please file the issue follow the template, or we won't help you to solve the problem.

## 0. Report Issue Guide

1. Please run the following command and check whether the problem has been fixed：
```
rm -rf package-lock.json
rm -rf node_modules
npm install
```

2. Please search in [FAQ List](https://wechaty.js.org/faq) first, and make sure your problem has not been solved before.

3. Please search in the issue first, and make sure your problem had not been reported before

## 1. Describe the bug
Give a clear and concise description of what the bug is.

I am running the [example code](https://github.com/juzibot/wxwork-tester) on my laptop, I got the following error messages:

```
16:27:53 ERR PuppetHostie startGrpcStream() connection failed and max retries has been reached. Error:
Error: Expected argument of type wechaty.puppet.EventRequest
    at serialize_wechaty_puppet_EventRequest (/Users/wuchong/projects/wework/node_modules/_wechaty@0.56.2@wechaty/node_modules/@chatie/grpc/dist/generated/wechaty/puppet_grpc_pb.js:294:11)
    at Object.final_requester.sendMessage (/Users/wuchong/projects/wework/node_modules/_wechaty@0.56.2@wechaty/node_modules/grpc/src/client_interceptors.js:1037:21)
    at InterceptingCall._callNext (/Users/wuchong/projects/wework/node_modules/_wechaty@0.56.2@wechaty/node_modules/grpc/src/client_interceptors.js:419:43)
    at InterceptingCall.sendMessage (/Users/wuchong/projects/wework/node_modules/_wechaty@0.56.2@wechaty/node_modules/grpc/src/client_interceptors.js:464:8)
    at InterceptingCall._callNext (/Users/wuchong/projects/wework/node_modules/_wechaty@0.56.2@wechaty/node_modules/grpc/src/client_interceptors.js:428:12)
    at InterceptingCall.sendMessage (/Users/wuchong/projects/wework/node_modules/_wechaty@0.56.2@wechaty/node_modules/grpc/src/client_interceptors.js:464:8)
    at ServiceClient.Client.makeServerStreamRequest (/Users/wuchong/projects/wework/node_modules/_wechaty@0.56.2@wechaty/node_modules/grpc/src/client.js:770:21)
    at ServiceClient.method_func [as event] (/Users/wuchong/projects/wework/node_modules/_wechaty@0.56.2@wechaty/node_modules/grpc/src/client.js:1003:43)
    at PuppetHostie.startGrpcStream (/Users/wuchong/projects/wework/node_modules/_wechaty@0.56.2@wechaty/node_modules/wechaty-puppet-hostie/src/client/puppet-hostie.ts:379:45)
```

## 2. To Reproduce
This part is very important: if you can not provide any reproduce steps, then the problem will be very hard to be recognized.

1. copy and then paste the code from [example code part](https://github.com/juzibot/wxwork-tester) and save it as main.ts
2. replace the token in the code which got from juzi.bot
3. save and run `npm install wechaty qrcode-terminal && ts-node main.ts` 

## 3. Full Output Logs
Set env `WECHATY_LOG=silly` in order to set log level to silly, then we can get the full log (If you dosen't set log env, log level is info as default, we cannot get the full log)

```shell
$ WECHATY_LOG=silly node yourbot.js

Question: Paste your FULL(DO NOT ONLY PROVIDE FRAGMENTS) log messages
Answer:

16:35:56 SILL Puppet Config: WECHATY_LOG set level to silly
16:35:56 INFO Config registering process.on("unhandledRejection") for development/debug
16:35:56 VERB Config constructor()
16:35:56 VERB Wechaty constructor()
16:35:56 VERB StateSwitch constructor(Wechaty, "{"log":{"enableTimestamp":true,"logLevel":5,"prefixFilter":{}}}")
16:35:56 VERB StateSwitch constructor(WechatyReady, "{"log":{"enableTimestamp":true,"logLevel":5,"prefixFilter":{}}}")
16:35:56 VERB Wechaty on(scan, listener) registering... listenerCount: 0
16:35:56 VERB Wechaty on(login, listener) registering... listenerCount: 0
16:35:56 VERB Wechaty on(message, listener) registering... listenerCount: 0
16:35:56 VERB Wechaty <wechaty-puppet-hostie>() start() v0.56.2 is starting...
16:35:56 VERB Wechaty id: ckkf6byi40000nv92ax5c187g
16:35:56 SILL StateSwitch <Wechaty> on() is false
16:35:56 SILL StateSwitch <WechatyReady> off() is true
16:35:56 VERB StateSwitch <WechatyReady> off(true) <- (true)
16:35:56 SILL StateSwitch <Wechaty> on() is false
16:35:56 VERB StateSwitch <Wechaty> on(pending) <- (false)
16:35:56 VERB MemoryCard constructor(undefined)
16:35:56 VERB MemoryCard getStorage() for storage type: N/A
16:35:56 VERB MemoryCard load() from storage: N/A
16:35:56 VERB MemoryCard load() no storage
16:35:56 VERB Wechaty initPuppet() wechaty-puppet-hostie
16:35:56 VERB MemoryCard multiplex(puppet)
16:35:56 VERB MemoryCard static multiplex(MemoryCard<>, puppet)
16:35:56 VERB MemoryCard constructor({"multiplex":{"name":"puppet","parent":{"payload":{},"multiplexNameList":[]}}})
16:35:56 VERB PuppetManager resolve({puppet: wechaty-puppet-hostie, puppetOptions: {"token":"puppet_wxwork_4b7f47a3a6d63a12"}})
16:35:56 VERB PuppetManager resolveName(wechaty-puppet-hostie)
16:35:56 VERB PuppetManager checkModule(wechaty-puppet-hostie)
16:35:56 SILL PuppetManager checkModule() wechaty-puppet-hostie installed version 0.12.257 satisfied range *
16:35:57 VERB Puppet constructor({"token":"puppet_wxwork_4b7f47a3a6d63a12"}) #0
16:35:57 VERB StateSwitch constructor(PuppetHostie, "{"log":{"enableTimestamp":true,"logLevel":5,"prefixFilter":{}}}")
16:35:57 VERB MemoryCard constructor(undefined)
16:35:57 VERB MemoryCard getStorage() for storage type: N/A
16:35:57 VERB MemoryCard load() from storage: N/A
16:35:57 VERB MemoryCard load() no storage
16:35:57 VERB Puppet constructor() watchdog timeout set to 60 seconds
16:35:57 VERB HotImport callerResolve(., /Users/wuchong/projects/wework/node_modules/_wechaty-puppet@0.33.8@wechaty-puppet/dist/src/puppet.js)
16:35:57 SILL HotImport callerResolve() callsites() file=/Users/wuchong/projects/wework/node_modules/_hot-import@0.2.14@hot-import/dist/src/hot-import.js, type=Object
16:35:57 SILL HotImport callerResolve() callsites() file=/Users/wuchong/projects/wework/node_modules/_wechaty-puppet@0.33.8@wechaty-puppet/dist/src/puppet.js, type=null
16:35:57 SILL HotImport callerResolve() callsites() file=/Users/wuchong/projects/wework/node_modules/_wechaty@0.56.2@wechaty/node_modules/wechaty-puppet-hostie/dist/src/client/puppet-hostie.js, type=null
16:35:57 SILL HotImport callerResolve() callerFile=/Users/wuchong/projects/wework/node_modules/_wechaty@0.56.2@wechaty/node_modules/wechaty-puppet-hostie/dist/src/client/puppet-hostie.js
16:35:57 VERB Puppet constructor() childClassPath=/Users/wuchong/projects/wework/node_modules/_wechaty@0.56.2@wechaty/node_modules/wechaty-puppet-hostie/dist/src/client
16:35:57 VERB Puppet setMemory()
16:35:57 VERB Wechaty initPuppetEventBridge(Puppet#0<PuppetHostie>())
16:35:57 VERB Wechaty initPuppetEventBridge() puppet.on(friendship) (listenerCount:0) registering...
16:35:57 VERB Wechaty initPuppetEventBridge() puppet.on(login) (listenerCount:0) registering...
16:35:57 VERB Wechaty initPuppetEventBridge() puppet.on(logout) (listenerCount:0) registering...
16:35:57 VERB Wechaty initPuppetEventBridge() puppet.on(message) (listenerCount:0) registering...
16:35:57 VERB Wechaty initPuppetEventBridge() puppet.on(room-invite) (listenerCount:0) registering...
16:35:57 VERB Wechaty initPuppetEventBridge() puppet.on(room-join) (listenerCount:0) registering...
16:35:57 VERB Wechaty initPuppetEventBridge() puppet.on(room-leave) (listenerCount:0) registering...
16:35:57 VERB Wechaty initPuppetEventBridge() puppet.on(room-topic) (listenerCount:0) registering...
16:35:57 VERB Wechaty initPuppetEventBridge() puppet.on(scan) (listenerCount:0) registering...
16:35:57 VERB Wechaty initPuppetEventBridge() puppet.on(dirty) (listenerCount:0) registering...
16:35:57 VERB Wechaty initPuppetEventBridge() puppet.on(dong) (listenerCount:0) registering...
16:35:57 VERB Wechaty initPuppetEventBridge() puppet.on(error) (listenerCount:0) registering...
16:35:57 VERB Wechaty initPuppetEventBridge() puppet.on(heartbeat) (listenerCount:0) registering...
16:35:57 VERB Wechaty initPuppetEventBridge() puppet.on(ready) (listenerCount:0) registering...
16:35:57 VERB Wechaty initPuppetEventBridge() puppet.on(reset) (listenerCount:0) registering...
16:35:57 VERB Wechaty wechatifyUserModules(Puppet#0<PuppetHostie>())
16:35:57 VERB PuppetHostie start()
16:35:57 SILL StateSwitch <PuppetHostie> on() is false
16:35:57 SILL StateSwitch <PuppetHostie> on() is false
16:35:57 VERB StateSwitch <PuppetHostie> on(pending) <- (false)
16:35:57 VERB PuppetHostie startGrpcClient()
16:35:57 VERB PuppetHostie discoverHostieIp(puppet_wxwork_4b7f47a3a6d63a12)
16:35:58 VERB PuppetHostie startGrpcStream()
16:35:58 VERB PuppetHostie startGrpcStream() connection failed, 4 retries left, reconnecting in 2 seconds...
16:36:00 VERB PuppetHostie startGrpcStream() connection failed, 3 retries left, reconnecting in 2 seconds...

```

## 4. Additional context

[bug]

**Comment by windmemory** [comment]
Please contact `Juzi.BOT` with your token to resolve this issue.
