### ISSUE TITLE
运行示例代码报错

### ISSUE THREAD

**Issue by atorber** [juzibot/wxwork-tester#35]
B000000152192P:wechat-assistant-pro-master luyuchao$ node WeCom_tool.js
16:50:50 WARN No endpoint when starting grpc client, 10 retry left. Reconnecting in 10 seconds... 
16:51:00 WARN No endpoint when starting grpc client, 9 retry left. Reconnecting in 10 seconds... 
SyntaxError: Unexpected token < in JSON at position 0
    at JSON.parse (<anonymous>)
    at IncomingMessage.<anonymous> (/Users/luyuchao/OneDrive/wxxcc/groupmaster/wechat-assistant-pro-master/node_modules/wechaty-puppet-service/dist/src/client/puppet-service.js:60:34)
    at IncomingMessage.emit (events.js:327:22)
    at IncomingMessage.EventEmitter.emit (domain.js:483:12)
    at endReadableNT (_stream_readable.js:1220:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)

**Comment by su-chang** [comment]
提供下wechaty的版本信息

**Comment by atorber** [comment]
"wechaty": "^0.57.19"

**Comment by su-chang** [comment]
token私聊发juzi bot哈

wechaty可以更新下  npm install wechaty@latest

**Comment by atorber** [comment]
更新最新版本后还是报错

B000000152192P:wechat-assistant-pro-master luyuchao$ node WeCom_tool.js
17:54:45 ERR PuppetService start() rejection: PuppetService discoverServiceIp() endpoint<https://api.chatie.io/v0/hosties/puppet_wxwork_893a781b8bdec1e1> rejection: Error: read ECONNRESET
Error: PuppetService discoverServiceIp() endpoint<https://api.chatie.io/v0/hosties/puppet_wxwork_893a781b8bdec1e1> rejection: Error: read ECONNRESET
    at ClientRequest.<anonymous> (/Users/luyuchao/OneDrive/wxxcc/groupmaster/wechat-assistant-pro-master/node_modules/wechaty-puppet-service/dist/src/client/puppet-service.js:62:24)
    at ClientRequest.emit (events.js:315:20)
    at ClientRequest.EventEmitter.emit (domain.js:483:12)
    at TLSSocket.socketErrorListener (_http_client.js:426:9)
    at TLSSocket.emit (events.js:315:20)
    at TLSSocket.EventEmitter.emit (domain.js:483:12)
    at emitErrorNT (internal/streams/destroy.js:92:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
Error: PuppetService discoverServiceIp() endpoint<https://api.chatie.io/v0/hosties/puppet_wxwork_893a781b8bdec1e1> rejection: Error: read ECONNRESET
    at ClientRequest.<anonymous> (/Users/luyuchao/OneDrive/wxxcc/groupmaster/wechat-assistant-pro-master/node_modules/wechaty-puppet-service/dist/src/client/puppet-service.js:62:24)
    at ClientRequest.emit (events.js:315:20)
    at ClientRequest.EventEmitter.emit (domain.js:483:12)
    at TLSSocket.socketErrorListener (_http_client.js:426:9)
    at TLSSocket.emit (events.js:315:20)
    at TLSSocket.EventEmitter.emit (domain.js:483:12)
    at emitErrorNT (internal/streams/destroy.js:92:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
17:54:45 ERR Wechaty start() exception: PuppetService discoverServiceIp() endpoint<https://api.chatie.io/v0/hosties/puppet_wxwork_893a781b8bdec1e1> rejection: Error: read ECONNRESET
(node:59807) UnhandledPromiseRejectionWarning: Error: PuppetService discoverServiceIp() endpoint<https://api.chatie.io/v0/hosties/puppet_wxwork_893a781b8bdec1e1> rejection: Error: read ECONNRESET
    at ClientRequest.<anonymous> (/Users/luyuchao/OneDrive/wxxcc/groupmaster/wechat-assistant-pro-master/node_modules/wechaty-puppet-service/dist/src/client/puppet-service.js:62:24)
    at ClientRequest.emit (events.js:315:20)
    at ClientRequest.EventEmitter.emit (domain.js:483:12)
    at TLSSocket.socketErrorListener (_http_client.js:426:9)
    at TLSSocket.emit (events.js:315:20)
    at TLSSocket.EventEmitter.emit (domain.js:483:12)
    at emitErrorNT (internal/streams/destroy.js:92:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
(node:59807) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:59807) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by su-chang** [comment]
现在试一下哈  应该可以了

**Comment by su-chang** [comment]
token暴露了 注意

**Comment by atorber** [comment]
删除那一条了，多谢，晚上我再试下
