### ISSUE TITLE
Bug dingDongBot-java程序无法启动

### ISSUE THREAD

**Issue by koreQAQ** [juzibot/wxwork-tester#49]
## dingdongtBot程序无法运行
环境：
1. java 1.8
2. wechaty 0.1.5-SNAPSHOT

构建工具: maven

1. Java代码：
```java
public class DingDongBot {

    public static void main(String[] args) throws Exception {

        String token = "d1c8e7ee4fcb4cc2a1e603b4a39603fc";
        WechatyOptions wechatyOptions = new WechatyOptions();
        wechatyOptions.setPuppet("wechaty-puppet-service");
        PuppetOptions puppetOptions = new PuppetOptions();
        puppetOptions.setToken(token);
        puppetOptions.setName("demo");
        wechatyOptions.setPuppetOptions(puppetOptions);

        Wechaty bot = Wechaty.instance(wechatyOptions);

        bot.onScan((qrcode, statusScanStatus, data) -> {
            System.out.println(QrcodeUtils.getQr(qrcode));
            System.out.println("Online Image: https://wechaty.github.io/qrcode/" + qrcode);
        });

        bot.onMessage(message -> {

            Contact from = message.from();
            Room room = message.room();
            String text = message.text();

            if (StringUtils.equals(text, "#ding")) {
                if (room != null) {
                    room.say("dong");
                } else {
                    from.say("dong");
                }
            }
        });

        bot.start(true);

    }
}
```
报错堆栈信息：
```shell
01:52:49.944 [main]INFO  io.github.wechaty.user.manager.PuppetManager-[23]  - PuppetManager resolveInstance({"name":"Wechaty","puppet":"wechaty-puppet-service","puppetOptions":{"token":"d1c8e7ee4fcb4cc2a1e603b4a39603fc","name":"demo"}})
01:52:50.532 [main]INFO  org.reflections.Reflections-[229]  - Reflections took 511 ms to scan 5 urls, producing 159 keys and 1545 values 
Exception in thread "main" java.util.NoSuchElementException: List is empty.
	at kotlin.collections.CollectionsKt___CollectionsKt.first(_Collections.kt:206)
	at io.github.wechaty.user.manager.PuppetManager$Companion.resolveInstance(PuppetManager.kt:40)
	at io.github.wechaty.Wechaty.initPuppet(Wechaty.kt:194)
	at io.github.wechaty.Wechaty.start(Wechaty.kt:51)
	at io.github.wechaty.DingDongBot.main(DingDongBot.java:58)
```

**Comment by koreQAQ** [comment]
切换到1.0.0-SNAPSHOT可以使用
