### ISSUE TITLE
发送小程序失败

### ISSUE THREAD

**Issue by ssl123** [juzibot/wxwork-tester#51]
---error-- 13 INTERNAL: ERR_SEND_MINI_PROGRAM can not send mini program without appid or pagePath or username. false
Error: 13 INTERNAL: ERR_SEND_MINI_PROGRAM can not send mini program without appid or pagePath or username.
    at Object.callErrorFromStatus (/home/www/node_modules/_@grpc_grpc-js@1.4.2@@grpc/grpc-js/src/call.ts:81:24)
    at Object.onReceiveStatus (/home/www/node_modules/_@grpc_grpc-js@1.4.2@@grpc/grpc-js/src/client.ts:343:36)
    at Object.onReceiveStatus (/home/www/node_modules/_@grpc_grpc-js@1.4.2@@grpc/grpc-js/src/client-interceptors.ts:430:34)
    at Object.onReceiveStatus (/home/www/node_modules/_@grpc_grpc-js@1.4.2@@grpc/grpc-js/src/client-interceptors.ts:392:48)
    at /home/www/node_modules/_@grpc_grpc-js@1.4.2@@grpc/grpc-js/src/call-stream.ts:299:24
    at processTicksAndRejections (node:internal/process/task_queues:78:11) {
  code: 13,
  details: 'ERR_SEND_MINI_PROGRAM can not send mini program without appid or pagePath or username.',
  metadata: Metadata { internalRepr: Map(0) {}, options: {} }
  

给群  快门科技研发组[R:10696052739024847]发送消息  {
"content":{"payload":{"appid":"gh_0aa444a25adc","title":"","pagePath":"routes/explore.html","description":"🌟京东自营","thumbUrl":"30590201000452305002010002041092541302033d0af802040b30feb602045df0c2c5042b777875706c6f61645f31373533353339353230344063686174726f6f6d3131355f313537363035393538390204010400030201000400","thumbKey":"42f8609e62817ae45cf7d8fefb532e83"}},"mentionList":[]}

**Comment by ssl123** [comment]
已解决
