### ISSUE TITLE
出现这个错误怎么处理

### ISSUE THREAD

**Issue by ssl123** [juzibot/wxwork-tester#53]
02:08:07 WARN Room findAll() room.ready() rejection:
Error: 13 INTERNAL: ERR_REQUEST_TIMEOUT ApiType: MT_QUERY_USER_INFO_MSG, requestId: 33b0a5f0-ef6f-461b-a20b-b7cbc44a4096, counter: 0
    at Object.callErrorFromStatus (/home/www/node_modules/_@grpc_grpc-js@1.4.2@@grpc/grpc-js/src/call.ts:81:24)
    at Object.onReceiveStatus (/home/www/node_modules/_@grpc_grpc-js@1.4.2@@grpc/grpc-js/src/client.ts:343:36)
    at Object.onReceiveStatus (/home/www/node_modules/_@grpc_grpc-js@1.4.2@@grpc/grpc-js/src/client-interceptors.ts:430:34)
    at Object.onReceiveStatus (/home/www/node_modules/_@grpc_grpc-js@1.4.2@@grpc/grpc-js/src/client-interceptors.ts:392:48)
    at /home/www/node_modules/_@grpc_grpc-js@1.4.2@@grpc/grpc-js/src/call-stream.ts:299:24
    at processTicksAndRejections (node:internal/process/task_queues:78:11)

**Comment by su-chang** [comment]
看起来像是对于一些已经不存在的群聊查询群成员信息时，提示查询超时。可以针对报错的群聊在手机端确认下是否存在。

**Comment by ssl123** [comment]
---error-- 13 INTERNAL: ERR_REQUEST_TIMEOUT ApiType: MT_QUERY_USER_INFO_MSG, requestId: f37b9628-c79c-4a8e-a778-c63739263365, counter: 0 false
Error: 13 INTERNAL: ERR_REQUEST_TIMEOUT ApiType: MT_QUERY_USER_INFO_MSG, requestId: f37b9628-c79c-4a8e-a778-c63739263365, counter: 0
    at Object.callErrorFromStatus (/home/www/node_modules/_@grpc_grpc-js@1.4.2@@grpc/grpc-js/src/call.ts:81:24)
    at Object.onReceiveStatus (/home/www/node_modules/_@grpc_grpc-js@1.4.2@@grpc/grpc-js/src/client.ts:343:36)
    at Object.onReceiveStatus (/home/www/node_modules/_@grpc_grpc-js@1.4.2@@grpc/grpc-js/src/client-interceptors.ts:430:34)
    at Object.onReceiveStatus (/home/www/node_modules/_@grpc_grpc-js@1.4.2@@grpc/grpc-js/src/client-interceptors.ts:392:48)
    at /home/www/node_modules/_@grpc_grpc-js@1.4.2@@grpc/grpc-js/src/call-stream.ts:299:24
    at processTicksAndRejections (node:internal/process/task_queues:78:11) {
  code: 13,
  details: 'ERR_REQUEST_TIMEOUT ApiType: MT_QUERY_USER_INFO_MSG, requestId: f37b9628-c79c-4a8e-a778-c63739263365, counter: 0',
  metadata: Metadata { internalRepr: Map(0) {}, options: {} }
}

**Comment by ssl123** [comment]
机器人的的数据可以清空吗，我是调用 所有群列表的接口的

**Comment by ssl123** [comment]
> 看起来像是对于一些已经不存在的群聊查询群成员信息时，提示查询超时。可以针对报错的群聊在手机端确认下是否存在。
有时候群发的时候还会有这种错误
---error-- 13 INTERNAL: ERR_REQUEST_TIMEOUT ApiType: MT_QUERY_USER_INFO_MSG, requestId: 1f4d81c9-a36e-4251-94fa-58b9fef3bd04, counter: 0 false
Error: 13 INTERNAL: ERR_REQUEST_TIMEOUT ApiType: MT_QUERY_USER_INFO_MSG, requestId: 1f4d81c9-a36e-4251-94fa-58b9fef3bd04, counter: 0
    at Object.callErrorFromStatus (/home/www/node_modules/_@grpc_grpc-js@1.4.2@@grpc/grpc-js/src/call.ts:81:24)
    at Object.onReceiveStatus (/home/www/node_modules/_@grpc_grpc-js@1.4.2@@grpc/grpc-js/src/client.ts:343:36)
    at Object.onReceiveStatus (/home/www/node_modules/_@grpc_grpc-js@1.4.2@@grpc/grpc-js/src/client-interceptors.ts:430:34)
    at Object.onReceiveStatus (/home/www/node_modules/_@grpc_grpc-js@1.4.2@@grpc/grpc-js/src/client-interceptors.ts:392:48)
    at /home/www/node_modules/_@grpc_grpc-js@1.4.2@@grpc/grpc-js/src/call-stream.ts:299:24
    at processTicksAndRejections (node:internal/process/task_queues:78:11) {
  code: 13,
  details: 'ERR_REQUEST_TIMEOUT ApiType: MT_QUERY_USER_INFO_MSG, requestId: 1f4d81c9-a36e-4251-94fa-58b9fef3bd04, counter: 0',
  metadata: Metadata { internalRepr: Map(0) {}, options: {} }

**Comment by ssl123** [comment]
> 看起来像是对于一些已经不存在的群聊查询群成员信息时，提示查询超时。可以针对报错的群聊在手机端确认下是否存在。
还要就是有时候发送消息也会超时
----
02:23:30 ERR PuppetService dirtyPayload() rejection: 13 INTERNAL: ERR_REQUEST_TIMEOUT ApiType: MT_QUERY_USER_INFO_MSG, requestId: 11344edf-4f5f-490e-abcd-6955c08d439b, counter: 0
---error-- 13 INTERNAL: ERR_REQUEST_TIMEOUT ApiType: MT_QUERY_USER_INFO_MSG, requestId: 11344edf-4f5f-490e-abcd-6955c08d439b, counter: 0 false
Error: 13 INTERNAL: ERR_REQUEST_TIMEOUT ApiType: MT_QUERY_USER_INFO_MSG, requestId: 11344edf-4f5f-490e-abcd-6955c08d439b, counter: 0
    at Object.callErrorFromStatus (/home/www/node_modules/_@grpc_grpc-js@1.4.2@@grpc/grpc-js/src/call.ts:81:24)
    at Object.onReceiveStatus (/home/www/node_modules/_@grpc_grpc-js@1.4.2@@grpc/grpc-js/src/client.ts:343:36)
    at Object.onReceiveStatus (/home/www/node_modules/_@grpc_grpc-js@1.4.2@@grpc/grpc-js/src/client-interceptors.ts:430:34)
    at Object.onReceiveStatus (/home/www/node_modules/_@grpc_grpc-js@1.4.2@@grpc/grpc-js/src/client-interceptors.ts:392:48)
    at /home/www/node_modules/_@grpc_grpc-js@1.4.2@@grpc/grpc-js/src/call-stream.ts:299:24
    at processTicksAndRejections (node:internal/process/task_queues:78:11) {
  code: 13,
  details: 'ERR_REQUEST_TIMEOUT ApiType: MT_QUERY_USER_INFO_MSG, requestId: 11344edf-4f5f-490e-abcd-6955c08d439b, counter: 0',
  metadata: Metadata { internalRepr: Map(0) {}, options: {} }
}

**Comment by ssl123** [comment]
> 看起来像是对于一些已经不存在的群聊查询群成员信息时，提示查询超时。可以针对报错的群聊在手机端确认下是否存在。

给群发送小程序有时候也会出错：  给群  13乌拉团丨粉丝福利团购群[R:10696052414021553]发送消息  {"content":{"payload":{"appid":"gh_b5403cc2567a@app","title":"快团团","pagePath":"pages/activity/activity.html?collection_activity_no=08s422nj4-W9VWFWqWpU1YMNzBc7zvHA&_x_group_user_no=QgdIqZGfYLyaCaNf45%2FCxw%3D%3D&ktt_share_style=activity_card_luxury_sense&ref_share_uid=7809141862428&ref_share_user_no=QgdIqZGfYLyaCaNf45%2FCxw%3D%3D&ref_share_channel=message&ref_share_id=d60b991d-5779-49b0-9801-4510aecbbb6c","description":"匠心出品，大型超市288元，直降189元，只需?99元鲍鱼花胶鸡带回家！家宴必备❗️送女性美容养颜！！?各大超市均有销售?\n【品珍鲜】姬松茸、竹荪、鲍鱼三大花胶鸡任选，花胶鲍鱼颗颗分明～\n高级的食材，美味又养颜，?花胶鸡汤火锅泡饭，煮面，怎么都好吃！","thumbUrl":"https://donut-docker.s3.cn-northwest-1.amazonaws.com.cn/mini_program_image/9684f8cc-8232-4610-b790-6d7f3737a8b1.jpg","username":"wx2672757b4553d5d7","thumbKey":"{\"aes_key\":\"626E63796F656A6270686C68616F6864\",\"file_id\":\"306b02010204643062020100020440a0365b02031e90380204d3c5f46d02046233da1c0436313038343234313439395f313135303634323435375f6632663566646439386264613933373461393332383638306638613764343064020100020303e1b004000201010201000400\",\"size\":254378}"}},"mentionList":[]}


02:23:30 ERR PuppetService dirtyPayload() rejection: 13 INTERNAL: ERR_REQUEST_TIMEOUT ApiType: MT_QUERY_USER_INFO_MSG, requestId: 11344edf-4f5f-490e-abcd-6955c08d439b, counter: 0
---error-- 13 INTERNAL: ERR_REQUEST_TIMEOUT ApiType: MT_QUERY_USER_INFO_MSG, requestId: 11344edf-4f5f-490e-abcd-6955c08d439b, counter: 0 false
Error: 13 INTERNAL: ERR_REQUEST_TIMEOUT ApiType: MT_QUERY_USER_INFO_MSG, requestId: 11344edf-4f5f-490e-abcd-6955c08d439b, counter: 0
    at Object.callErrorFromStatus (/home/www/node_modules/_@grpc_grpc-js@1.4.2@@grpc/grpc-js/src/call.ts:81:24)
    at Object.onReceiveStatus (/home/www/node_modules/_@grpc_grpc-js@1.4.2@@grpc/grpc-js/src/client.ts:343:36)
    at Object.onReceiveStatus (/home/www/node_modules/_@grpc_grpc-js@1.4.2@@grpc/grpc-js/src/client-interceptors.ts:430:34)
    at Object.onReceiveStatus (/home/www/node_modules/_@grpc_grpc-js@1.4.2@@grpc/grpc-js/src/client-interceptors.ts:392:48)
    at /home/www/node_modules/_@grpc_grpc-js@1.4.2@@grpc/grpc-js/src/call-stream.ts:299:24
    at processTicksAndRejections (node:internal/process/task_queues:78:11) {
  code: 13,
  details: 'ERR_REQUEST_TIMEOUT ApiType: MT_QUERY_USER_INFO_MSG, requestId: 11344edf-4f5f-490e-abcd-6955c08d439b, counter: 0',
  metadata: Metadata { internalRepr: Map(0) {}, options: {} }
}

**Comment by su-chang** [comment]
> 机器人的的数据可以清空吗，我是调用 所有群列表的接口的

已清除缓存，需要重新扫码登录下试试。

**Comment by ssl123** [comment]
> > 机器人的的数据可以清空吗，我是调用 所有群列表的接口的

谢谢，现在群列表可以加载了，我在观察下群发消息的问题
