### ISSUE TITLE
start:service后无事件监听，WatchdogAgent reset？

### ISSUE THREAD

**Issue by qianjujie** [juzibot/wxwork-tester#55]
前面log省略
========================
12:41:49 VERB Wechaty onStart() ... done
12:41:49 VERB ServiceCtl<Wechaty> start() this.onStart() ... done
12:41:49 VERB StateSwitch <Wechaty> active(true) <- (pending)
12:41:49 VERB ServiceCtl<Wechaty> start() ... done
12:41:49 INFO StarterBot Starter Bot Started.
12:42:19 VERB PuppetService onGrpcStreamEvent({type:EVENT_TYPE_HEARTBEAT(1), payload(len:62)})
12:42:49 VERB PuppetService onGrpcStreamEvent({type:EVENT_TYPE_HEARTBEAT(1), payload(len:62)})
12:43:19 VERB PuppetService onGrpcStreamEvent({type:EVENT_TYPE_HEARTBEAT(1), payload(len:62)})
12:43:49 VERB PuppetService onGrpcStreamEvent({type:EVENT_TYPE_HEARTBEAT(1), payload(len:62)})
12:44:19 VERB PuppetService onGrpcStreamEvent({type:EVENT_TYPE_HEARTBEAT(1), payload(len:62)})
12:44:49 VERB PuppetService onGrpcStreamEvent({type:EVENT_TYPE_HEARTBEAT(1), payload(len:62)})
12:45:19 VERB PuppetService onGrpcStreamEvent({type:EVENT_TYPE_HEARTBEAT(1), payload(len:62)})
12:45:49 VERB PuppetService onGrpcStreamEvent({type:EVENT_TYPE_HEARTBEAT(1), payload(len:62)})
12:46:19 VERB PuppetService onGrpcStreamEvent({type:EVENT_TYPE_HEARTBEAT(1), payload(len:62)})
12:46:49 VERB PuppetService onGrpcStreamEvent({type:EVENT_TYPE_HEARTBEAT(1), payload(len:62)})
12:47:19 VERB PuppetService onGrpcStreamEvent({type:EVENT_TYPE_HEARTBEAT(1), payload(len:62)})
12:47:49 VERB PuppetService onGrpcStreamEvent({type:EVENT_TYPE_HEARTBEAT(1), payload(len:62)})
12:48:19 VERB PuppetService onGrpcStreamEvent({type:EVENT_TYPE_HEARTBEAT(1), payload(len:62)})
12:48:44 VERB PuppetService bridgeGrpcEventStream() eventStream.on(end)
**_12:49:19 WARN PuppetWatchdogAgent start() reset() reason: {"data":"wecom event trigger heartbeat event","timeoutMilliseconds":60000}
GError: WatchdogAgent reset: lastFood: "{"data":"wecom event trigger heartbeat event","timeoutMilliseconds":60000}"
    at Watchdog.reset (file:///H:/git_lib/wechaty/node_modules/wechaty-puppet/src/agents/watchdog-agent.ts:65:33)
    at Watchdog.emit (node:events:526:28)
    at Watchdog.emit (node:domain:475:12)
    at Timeout._onTimeout (file:///H:/git_lib/wechaty/node_modules/watchdog/src/watchdog.ts:115:12)
    at listOnTimeout (node:internal/timers:559:17)
    at processTimers (node:internal/timers:502:7) {
  code: 2,
  details: 'Error: WatchdogAgent reset: lastFood: "{"data":"wecom event trigger 
heartbeat event","timeoutMilliseconds":60000}"\n' +
    '    at Watchdog.reset (file:///H:/git_lib/wechaty/node_modules/wechaty-puppet/src/agents/watchdog-agent.ts:65:33)\n' +
    '    at Watchdog.emit (node:events:526:28)\n' +
    '    at Watchdog.emit (node:domain:475:12)\n' +
    '    at Timeout._onTimeout (file:///H:/git_lib/wechaty/node_modules/watchdog/src/watchdog.ts:115:12)\n' +
    '    at listOnTimeout (node:internal/timers:559:17)\n' +
    '    at processTimers (node:internal/timers:502:7)'
}_**
12:49:19 VERB ServiceCtl<PuppetServiceMixin> reset()
12:49:19 VERB StateSwitch <PuppetServiceMixinReset> active(true) <- (false)     
12:49:19 VERB ServiceCtl<PuppetServiceMixin> reset() wait state ready() ...     
12:49:19 VERB StateSwitch <PuppetServiceMixin> stable(undefined, noCross=false) 
12:49:19 VERB ServiceCtl<PuppetServiceMixin> reset() wait state ready() ... done12:49:19 VERB ReadyMixin stop()
12:49:19 VERB PuppetServiceMixin stop()
12:49:19 VERB PuppetWatchdogAgent start() "heartbeat" event listener removed    
12:49:19 VERB PuppetWatchdogAgent start() "reset" event listener removed        
12:49:19 VERB ServiceCtl<PuppetServiceMixin> stop()
12:49:19 VERB StateSwitch <PuppetServiceMixin> inactive(pending) <- (false)     
12:49:19 VERB ServiceCtl<PuppetServiceMixin> stop() this.onStop() ...
12:49:19 VERB PuppetService onStop()
12:49:19 VERB PuppetService onStop() stopping grpc manager ...
12:49:19 VERB GrpcManager stop()
12:49:19 VERB GrpcManager stop() stop stream ...
12:49:19 VERB GrpcManager stopStream()
12:49:19 VERB GrpcManager stopStream() destroying event stream ...
12:49:19 VERB GrpcManager stopStream() destroying event stream ... done
12:49:19 VERB GrpcManager stop() stop stream ... done
12:49:19 VERB GrpcManager stop() stop client ...
GError: 14 UNAVAILABLE: No connection established
    at Object.callErrorFromStatus (H:\git_lib\wechaty\node_modules\@grpc\grpc-js\src\call.ts:81:24)
    at Object.onReceiveStatus (H:\git_lib\wechaty\node_modules\@grpc\grpc-js\src\client.ts:343:36)
    at Object.onReceiveStatus (H:\git_lib\wechaty\node_modules\@grpc\grpc-js\src\client-interceptors.ts:462:34)
    at Object.onReceiveStatus (H:\git_lib\wechaty\node_modules\@grpc\grpc-js\src\client-interceptors.ts:424:48)
    at H:\git_lib\wechaty\node_modules\@grpc\grpc-js\src\call-stream.ts:330:24  
    at processTicksAndRejections (node:internal/process/task_queues:78:11) {    
  code: 14,
  details: 'No connection established'
}
12:49:23 VERB GrpcManager stop() destroy client ...
12:49:23 VERB GrpcManager destroyClient()
12:49:23 VERB GrpcManager stop() destroy client ... done
12:49:23 VERB GrpcManager stop() ... done
12:49:23 VERB PuppetService onStop() stopping grpc manager ... done
12:49:23 VERB PuppetService onStop() ... done
12:49:23 VERB ServiceCtl<PuppetServiceMixin> stop() this.onStop() ... done      
12:49:23 VERB ServiceCtl<PuppetServiceMixin> stop() super.stop() ...
12:49:23 VERB PuppetCacheMixin stop()
12:49:23 VERB PuppetCacheAgent stop()
12:49:23 VERB PuppetCacheAgent clear()
12:49:23 VERB PuppetLoginMixin stop()
12:49:23 VERB PuppetService logout()
12:49:23 VERB PuppetLoginMixin logout(logout())
12:49:23 VERB PuppetLoginMixin logout() isLoggedIn === false, do nothing        
12:49:23 VERB PuppetMemoryMixin stop()
12:49:23 VERB PuppetSkeleton stop()
12:49:23 VERB ServiceCtl<PuppetServiceMixin> stop() super.stop() ... done       
12:49:23 VERB StateSwitch <PuppetServiceMixin> inactive(true) <- (pending)      
12:49:23 VERB ServiceCtl<PuppetServiceMixin> stop() ... done
12:49:23 VERB ReadyMixin start()
12:49:23 VERB PuppetServiceMixin start()
12:49:23 VERB ServiceCtl<PuppetServiceMixin> start()
12:49:23 VERB StateSwitch <PuppetServiceMixin> active(pending) <- (false)       
12:49:23 VERB ServiceCtl<PuppetServiceMixin> start() super.start() ...
12:49:23 VERB PuppetCacheMixin start()
12:49:23 VERB PuppetLoginMixin start()
12:49:23 VERB PuppetMemoryMixin start()
12:49:23 VERB PuppetSkeleton start()
12:49:23 VERB PuppetCacheAgent start()
12:49:23 VERB PuppetCacheMixin start() "dirty" event listener added
12:49:23 VERB ServiceCtl<PuppetServiceMixin> start() super.start() ... done     
12:49:23 VERB ServiceCtl<PuppetServiceMixin> start() this.onStart() ...
12:49:23 VERB PuppetService onStart()
12:49:23 VERB PuppetService start() instanciating GrpcManager ...
12:49:23 VERB GrpcManager constructor({"endpoint":"52.229.135.43:8088","token":"insercure_75a4238a-94a9-4d77-99b1-a75c09923e40"})
12:49:23 VERB GrpcManager constructor() tlsRootCert(hash): "88ab8b62777f0fb1179ec567c5019c31d646428cc0a3fdb007fcffa1e9fac5a8"
12:49:23 VERB GrpcManager constructor() token: "insercure_75a4238a-94a9-4d77-99b1-a75c09923e40"
12:49:23 VERB GrpcManager constructor() endpoint: "52.229.135.43:8088"
12:49:23 VERB GrpcManager constructor() disableTls: "true"
12:49:23 VERB GrpcManager constructor() serverName(SNI): "insercure"
12:49:23 VERB PuppetService start() instanciating GrpcManager ... done
12:49:23 VERB PuppetService start() setting up bridge grpc event stream ...     
12:49:23 VERB PuppetService bridgeGrpcEventStream(client)
12:49:23 VERB PuppetService start() setting up bridge grpc event stream ... done12:49:23 VERB PuppetService start() starting grpc manager...
12:49:23 VERB GrpcManager start()
12:49:23 VERB GrpcManager start() initializing client ...
12:49:23 VERB GrpcManager initClient()
12:49:23 WARN GrpcManager initClient() TLS: disabled (INSECURE)
12:49:23 VERB GrpcManager initClient() ... done
12:49:23 VERB GrpcManager start() initializing client ... done
12:49:23 VERB GrpcManager start() starting stream ...
12:49:23 VERB GrpcManager startStream()
12:49:23 VERB GrpcManager startStream() grpc -> event() ...
12:49:23 VERB GrpcManager startStream() grpc -> event() ... done
12:49:23 VERB GrpcManager startStream() grpc -> event peeking data or timeout ...
12:49:23 VERB PuppetCacheMixin start() "dirty" event listener removed
12:49:26 VERB GrpcManager startStream() grpc -> event peeking data or timeout ... timeout
12:49:26 VERB GrpcManager startStream() grpc -> event peeking data or timeout ... data peeked
12:49:26 VERB GrpcManager startStream() initializing event stream ...
12:49:26 VERB GrpcManager startStream() initializing event stream ... done      
12:49:26 VERB GrpcManager startStream() ... done
12:49:26 VERB GrpcManager start() starting stream ... done
12:49:26 VERB GrpcManager start() calling grpc server: start() ...
12:49:36 VERB GrpcManager start() calling grpc server: start() ... done
12:49:36 VERB GrpcManager start() ... done
12:49:36 VERB PuppetService start() starting grpc manager... done
12:49:36 VERB PuppetService onStart() ... done
12:49:36 VERB ServiceCtl<PuppetServiceMixin> start() this.onStart() ... done    
12:49:36 VERB StateSwitch <PuppetServiceMixin> active(true) <- (pending)        
12:49:36 VERB ServiceCtl<PuppetServiceMixin> start() ... done
12:49:36 VERB PuppetWatchdogAgent start() "heartbeat" event listener added      
12:49:36 VERB PuppetWatchdogAgent start() "reset" event listener added
12:49:36 VERB StateSwitch <PuppetServiceMixinReset> inactive(true) <- (false)   
12:49:36 VERB ServiceCtl<PuppetServiceMixin> reset() ... done

**Comment by su-chang** [comment]
请参考这个项目运行：https://github.com/wechaty/getting-started

**Comment by qianjujie** [comment]
是基于getting-started运行的
