### ISSUE TITLE
新token无法发图片，并且报错

### ISSUE THREAD

**Issue by phillipyuan** [juzibot/wxwork-tester#62]
![77d4e875d6a08a43e2cfefb33cc9967](https://user-images.githubusercontent.com/26888403/180110958-86504867-5c91-432d-85b9-6c4be37991ea.png)

报错信息如下：
Jul 21 09:05:08 zhfi-prd-gitlab ts-node[14793]: (node:14793) UnhandledPromiseRejectionWarning: Error: 2 UNKNOWN: Error: no url
Jul 21 09:05:08 zhfi-prd-gitlab ts-node[14793]: at new FileBox (C:\juzi\node_modules\file-box\dist\cjs\src\file-box.js:392:27)
Jul 21 09:05:08 zhfi-prd-gitlab ts-node[14793]: at new FileBox (C:\juzi\node_modules\clone-class\dist\cjs\src\clone-class.js:23:13)
Jul 21 09:05:08 zhfi-prd-gitlab ts-node[14793]: at Function.fromUrl (C:\juzi\node_modules\file-box\dist\cjs\src\file-box.js:113:16)
Jul 21 09:05:08 zhfi-prd-gitlab ts-node[14793]: at Function.fromJSON (C:\juzi\node_modules\file-box\dist\cjs\src\file-box.js:256:32)
Jul 21 09:05:08 zhfi-prd-gitlab ts-node[14793]: at messageSendFile (C:\juzi\node_modules\@juzi\wechaty-puppet-service\dist\cjs\src\server\puppet-implementation.js:723:45)
Jul 21 09:05:08 zhfi-prd-gitlab ts-node[14793]: at Object.messageSendFile (C:\juzi\node_modules\@juzi\wechaty-puppet-service\dist\cjs\src\auth\auth-impl-token.js:29:28)
Jul 21 09:05:08 zhfi-prd-gitlab ts-node[14793]: at handleUnary (C:\juzi\node_modules\@grpc\grpc-js\build\src\server.js:688:13)
Jul 21 09:05:08 zhfi-prd-gitlab ts-node[14793]: at processTicksAndRejections (node:internal/process/task_queues:96:5)
Jul 21 09:05:08 zhfi-prd-gitlab ts-node[14793]: at Object.callErrorFromStatus (/mnt/my-donut/node_modules/@grpc/grpc-js/src/call.ts:81:24)
Jul 21 09:05:08 zhfi-prd-gitlab ts-node[14793]: at Object.onReceiveStatus (/mnt/my-donut/node_modules/@grpc/grpc-js/src/client.ts:338:36)
Jul 21 09:05:08 zhfi-prd-gitlab ts-node[14793]: at Object.onReceiveStatus (/mnt/my-donut/node_modules/@grpc/grpc-js/src/client-interceptors.ts:426:34)
Jul 21 09:05:08 zhfi-prd-gitlab ts-node[14793]: at Object.onReceiveStatus (/mnt/my-donut/node_modules/@grpc/grpc-js/src/client-interceptors.ts:389:48)
Jul 21 09:05:08 zhfi-prd-gitlab ts-node[14793]: at process.nextTick (/mnt/my-donut/node_modules/@grpc/grpc-js/src/call-stream.ts:276:24)
Jul 21 09:05:08 zhfi-prd-gitlab ts-node[14793]: at process._tickCallback (internal/process/next_tick.js:61:11)
Jul 21 09:05:08 zhfi-prd-gitlab ts-node[14793]: (node:14793) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 28)

**Comment by phillipyuan** [comment]
切回旧版本才行
