### ISSUE TITLE
Please replace `wechaty` module by `@juzi/wechaty` module, and then try again.

### ISSUE THREAD

**Issue by ssl123** [juzibot/wxwork-tester#68]
换了之后接受消息有问题了 
/Users/shenlin/Desktop/html/wechaty-getting-started/node_modules/gerror/src/gerror/gerror.ts:69
      const e = new Error(payload)
                ^
GError: message not found for id: 1080471
    at Function.from (/Users/shenlin/Desktop/html/wechaty-getting-started/node_modules/gerror/src/gerror/gerror.ts:69:17)
    at PuppetService.<anonymous> (/Users/shenlin/Desktop/html/wechaty-getting-started/node_modules/@juzi/wechaty/src/wechaty-mixins/puppet-mixin.ts:281:45)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  code: 2,
  details: 'GError: message not found for id: 1080471\n' +
    '    at Function.from (/Users/shenlin/Desktop/html/wechaty-getting-started/node_modules/gerror/src/gerror/gerror.ts:69:17)\n' +
    '    at PuppetService.<anonymous> (/Users/shenlin/Desktop/html/wechaty-getting-started/node_modules/@juzi/wechaty/src/wechaty-mixins/puppet-mixin.ts:281:45)\n' +
    '    at processTicksAndRejections (node:internal/process/task_queues:96:5)'
}

**Comment by ssl123** [comment]
2
