### ISSUE TITLE
服务启动后间歇性异常宕机

### ISSUE THREAD

**Issue by 1334310385** [juzibot/wxwork-tester#74]
每天都要重启好几次服务，重启完可以正常运营，但是后间歇性停机，发现报错信息如下：
 UnhandledPromiseRejectionWarning: Error: 2 UNKNOWN: Error: ERR_INVALID_CONTACT_ID all ids should be number, R:10696050457047333 is not a number.
    at DataManager.<anonymous> (C:\juzi\node_modules\@juzibot\wechaty-puppet-wxwork\dist\src\work\data\data-manager.js:936:23)
    at Generator.next (<anonymous>)
    at C:\juzi\node_modules\@juzibot\wechaty-puppet-wxwork\dist\src\work\data\data-manager.js:31:71
    at new Promise (<anonymous>)
    at __awaiter (C:\juzi\node_modules\@juzibot\wechaty-puppet-wxwork\dist\src\work\data\data-manager.js:27:12)
    at DataManager.getContact (C:\juzi\node_modules\@juzibot\wechaty-puppet-wxwork\dist\src\work\data\data-manager.js:934:16)
    at DataManager.<anonymous> (C:\juzi\node_modules\@juzibot\wechaty-puppet-wxwork\dist\src\work\data\data-manager.js:927:40)
    at Generator.next (<anonymous>)
    at C:\juzi\node_modules\@juzibot\wechaty-puppet-wxwork\dist\src\work\data\data-manager.js:31:71
    at new Promise (<anonymous>)
    at Object.callErrorFromStatus (/root/tsf-agent/exec/1255000015/application-zbyx8kal/group-egyq9dv5/node_modules/_@grpc_grpc-js@1.6.12@@grpc/grpc-js/build/src/call.js:31:19)
    at Object.onReceiveStatus (/root/tsf-agent/exec/1255000015/application-zbyx8kal/group-egyq9dv5/node_modules/_@grpc_grpc-js@1.6.12@@grpc/grpc-js/build/src/client.js:190:52)
    at Object.onReceiveStatus (/root/tsf-agent/exec/1255000015/application-zbyx8kal/group-egyq9dv5/node_modules/_@grpc_grpc-js@1.6.12@@grpc/grpc-js/build/src/client-interceptors.js:365:141)
    at Object.onReceiveStatus (/root/tsf-agent/exec/1255000015/application-zbyx8kal/group-egyq9dv5/node_modules/_@grpc_grpc-js@1.6.12@@grpc/grpc-js/build/src/client-interceptors.js:328:181)
    at /root/tsf-agent/exec/1255000015/application-zbyx8kal/group-egyq9dv5/node_modules/_@grpc_grpc-js@1.6.12@@grpc/grpc-js/build/src/call-stream.js:188:78
    at processTicksAndRejections (internal/process/task_queues.js:75:11)
for call at
    at ServiceClientImpl.makeUnaryRequest (/root/tsf-agent/exec/1255000015/application-zbyx8kal/group-egyq9dv5/node_modules/_@grpc_grpc-js@1.6.12@@grpc/grpc-js/build/src/client.js:160:30)
    at ServiceClientImpl.contactPayload (/root/tsf-agent/exec/1255000015/application-zbyx8kal/group-egyq9dv5/node_modules/_@grpc_grpc-js@1.6.12@@grpc/grpc-js/build/src/make-client.js:105:19)
    at internal/util.js:297:30
    at new Promise (<anonymous>)
    at bound  (internal/util.js:296:12)
    at PuppetService.contactRawPayload (/root/tsf-agent/exec/1255000015/application-zbyx8kal/group-egyq9dv5/node_modules/_wechaty-puppet-service@0.21.11@wechaty-puppet-service/dist/src/client/puppet-ser
vice.js:481:110)
    at PuppetService.contactPayload (/root/tsf-agent/exec/1255000015/application-zbyx8kal/group-egyq9dv5/node_modules/_wechaty-puppet@0.41.9@wechaty-puppet/dist/src/puppet.js:453:39)
    at WechatifiedContact.ready (/root/tsf-agent/exec/1255000015/application-zbyx8kal/group-egyq9dv5/node_modules/_wechaty@0.62.3@wechaty/dist/src/user/contact.js:643:54)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async WechatifiedContact.sync (/root/tsf-agent/exec/1255000015/application-zbyx8kal/group-egyq9dv5/node_modules/_wechaty@0.62.3@wechaty/dist/src/user/contact.js:623:9)
    at async PuppetService.<anonymous> (/root/tsf-agent/exec/1255000015/application-zbyx8kal/group-egyq9dv5/node_modules/_wechaty@0.62.3@wechaty/dist/src/wechaty.js:431:37)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:17084) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which wa
s not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_
mode). (rejection id: 1)
(node:17084) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit cod
e.
(node:17084) [DEP0066] DeprecationWarning: OutgoingMessage.prototype._headers is deprecated

**Comment by 1334310385** [comment]
在这里提问题没人回复吗

**Comment by hcfw007** [comment]
这个问题应该不会影响运行吧。请参考https://github.com/juzibot/wechaty/issues/12。这个报错应该是由这个问题引起的。这个报错在wxwork内部应该是包住了的，不会影响运行。
可以考虑实现errorListener来handle错误，或者使用@juzi scope的wechaty，修复了此问题。
