### ISSUE TITLE
TypeError: response.getAdditionalInfo is not a function

### ISSUE THREAD

**Issue by xmsz** [juzibot/wxwork-tester#77]
> Important：Please file the issue follow the template, or we won't help you to solve the problem.

## 0. Report Issue Guide

1. Please run the following command and check whether the problem has been fixed：
```
rm -rf package-lock.json
rm -rf node_modules
npm install
```

2. Please search in [FAQ List](https://wechaty.js.org/faq) first, and make sure your problem has not been solved before.

3. Please search in the issue first, and make sure your problem had not been reported before

## 1. Describe the bug
机器人报错`TypeError: response.getAdditionalInfo is not a function`

## 2. To Reproduce
This part is very important: if you can not provide any reproduce steps, then the problem will be very hard to be recognized.

1. run '...'
2. ...
3. ...

## 3. Full Output Logs
Set env `WECHATY_LOG=silly` in order to set log level to silly, then we can get the full log (If you dosen't set log env, log level is info as default, we cannot get the full log)

**We need full log instead of log screenshot or log fragments!**

<details>
<summary>
Show Logs
</summary>

```shell
{"code":2,"details":"TypeError: response.getAdditionalInfo is not a function\n    at PuppetService.contactRawPayload (/var/lib/jenkins/workspace/机器人/app/app/node_modules/.pnpm/@juzi+wechaty-puppet-service@1.0.22_vjjry6o6ns7pjuvckltyjoewrm/node_modules/@juzi/wechaty-puppet-service/dist/cjs/src/client/puppet-service.js:533:38)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at async PuppetService.contactPayload (/var/lib/jenkins/workspace/机器人/app/app/node_modules/.pnpm/@juzi+wechaty-puppet@1.0.31/node_modules/@juzi/wechaty-puppet/dist/cjs/src/mixins/contact-mixin.js:195:32)\n    at async WechatifiedUserClass.ready (/var/lib/jenkins/workspace/机器人/app/app/node_modules/.pnpm/@juzi+wechaty@1.0.29_2wkbsofotjmsjkgdc6xphaef7m/node_modules/@juzi/wechaty/dist/cjs/src/user-modules/contact.js:608:28)\n    at async Function.find (/var/lib/jenkins/workspace/机器人/app/app/node_modules/.pnpm/@juzi+wechaty@1.0.29_2wkbsofotjmsjkgdc6xphaef7m/node_modules/@juzi/wechaty/dist/cjs/src/user-modules/contact.js:102:17)\n    at async doReady (/var/lib/jenkins/workspace/机器人/app/app/node_modules/.pnpm/@juzi+wechaty@1.0.29_2wkbsofotjmsjkgdc6xphaef7m/node_modules/@juzi/wechaty/dist/cjs/src/user-modules/room.js:239:17)\n    at async /var/lib/jenkins/workspace/机器人/app/app/node_modules/.pnpm/rx-queue@1.0.5/node_modules/rx-queue/dist/cjs/src/concurrency-executor/concurrency-executer.js:19:24","message":"response.getAdditionalInfo is not a function","name":"TypeError","stack":"TypeError: response.getAdditionalInfo is not a function\n    at PuppetService.contactRawPayload (/var/lib/jenkins/workspace/机器人/app/app/node_modules/.pnpm/@juzi+wechaty-puppet-service@1.0.22_vjjry6o6ns7pjuvckltyjoewrm/node_modules/@juzi/wechaty-puppet-service/dist/cjs/src/client/puppet-service.js:533:38)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at async PuppetService.contactPayload (/var/lib/jenkins/workspace/机器人/app/app/node_modules/.pnpm/@juzi+wechaty-puppet@1.0.31/node_modules/@juzi/wechaty-puppet/dist/cjs/src/mixins/contact-mixin.js:195:32)\n    at async WechatifiedUserClass.ready (/var/lib/jenkins/workspace/机器人/app/app/node_modules/.pnpm/@juzi+wechaty@1.0.29_2wkbsofotjmsjkgdc6xphaef7m/node_modules/@juzi/wechaty/dist/cjs/src/user-modules/contact.js:608:28)\n    at async Function.find (/var/lib/jenkins/workspace/机器人/app/app/node_modules/.pnpm/@juzi+wechaty@1.0.29_2wkbsofotjmsjkgdc6xphaef7m/node_modules/@juzi/wechaty/dist/cjs/src/user-modules/contact.js:102:17)\n    at async doReady (/var/lib/jenkins/workspace/机器人/app/app/node_modules/.pnpm/@juzi+wechaty@1.0.29_2wkbsofotjmsjkgdc6xphaef7m/node_modules/@juzi/wechaty/dist/cjs/src/user-modules/room.js:239:17)\n    at async /var/lib/jenkins/workspace/机器人/app/app/node_modules/.pnpm/rx-queue@1.0.5/node_modules/rx-queue/dist/cjs/src/concurrency-executor/concurrency-executer.js:19:24"}

```

</details>

## 4. Additional context

[bug]

**Comment by xmsz** [comment]
应该是依赖冲突问题
