### ISSUE TITLE
经常报message not found for id: xxxx

### ISSUE THREAD

**Issue by xmsz** [juzibot/wxwork-tester#78]
> Important：Please file the issue follow the template, or we won't help you to solve the problem.

## 0. Report Issue Guide

1. Please run the following command and check whether the problem has been fixed：
```
rm -rf package-lock.json
rm -rf node_modules
npm install
```

2. Please search in [FAQ List](https://wechaty.js.org/faq) first, and make sure your problem has not been solved before.

3. Please search in the issue first, and make sure your problem had not been reported before

## 1. Describe the bug
经常报GError: message not found for id: xxx

## 2. To Reproduce
This part is very important: if you can not provide any reproduce steps, then the problem will be very hard to be recognized.

1. run '...'
2. ...
3. ...

## 3. Full Output Logs
Set env `WECHATY_LOG=silly` in order to set log level to silly, then we can get the full log (If you dosen't set log env, log level is info as default, we cannot get the full log)

**We need full log instead of log screenshot or log fragments!**

<details>
<summary>
Show Logs
</summary>

```shell
{"code":2,"details":"GError: message not found for id: 1033040\n    at Function.from (/var/lib/jenkins/workspace/机器人/app/app/node_modules/.pnpm/gerror@1.0.16/node_modules/gerror/dist/cjs/src/gerror/gerror.js:86:23)\n    at PuppetService.<anonymous> (/var/lib/jenkins/workspace/机器人/app/app/node_modules/.pnpm/@juzi+wechaty@1.0.29_2wkbsofotjmsjkgdc6xphaef7m/node_modules/@juzi/wechaty/dist/cjs/src/wechaty-mixins/puppet-mixin.js:244:72)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)","message":"message not found for id: 1033040","name":"GError","stack":"GError: message not found for id: 1033040\n    at Function.from (/var/lib/jenkins/workspace/机器人/app/app/node_modules/.pnpm/gerror@1.0.16/node_modules/gerror/dist/cjs/src/gerror/gerror.js:86:23)\n    at PuppetService.<anonymous> (/var/lib/jenkins/workspace/机器人/app/app/node_modules/.pnpm/@juzi+wechaty@1.0.29_2wkbsofotjmsjkgdc6xphaef7m/node_modules/@juzi/wechaty/dist/cjs/src/wechaty-mixins/puppet-mixin.js:244:72)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)"}
```

</details>

## 4. Additional context

[bug]

**Comment by xmsz** [comment]
依赖冲突问题
